// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3jIkT9ChrFeo_ccPKfbwkb4us9a9VVZw',
    appId: '1:296427698232:web:9bc31981d57c703d904ecd',
    messagingSenderId: '296427698232',
    projectId: 'soundpad-1e6f6',
    authDomain: 'soundpad-1e6f6.firebaseapp.com',
    storageBucket: 'soundpad-1e6f6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYPmU0RDrXp5Dj0L3_jm_SdCoy9tqrpF8',
    appId: '1:296427698232:android:824f16c993299ee3904ecd',
    messagingSenderId: '296427698232',
    projectId: 'soundpad-1e6f6',
    storageBucket: 'soundpad-1e6f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYCblLaLQs5vyA3WQ_mqKTEqkLXanDP-g',
    appId: '1:296427698232:ios:350906f63eda5dda904ecd',
    messagingSenderId: '296427698232',
    projectId: 'soundpad-1e6f6',
    storageBucket: 'soundpad-1e6f6.appspot.com',
    iosClientId: '296427698232-da6i5tmusqm01t51bq9nmvs8ej3ikarg.apps.googleusercontent.com',
    iosBundleId: 'com.example.touchBarSoundpad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYCblLaLQs5vyA3WQ_mqKTEqkLXanDP-g',
    appId: '1:296427698232:ios:350906f63eda5dda904ecd',
    messagingSenderId: '296427698232',
    projectId: 'soundpad-1e6f6',
    storageBucket: 'soundpad-1e6f6.appspot.com',
    iosClientId: '296427698232-da6i5tmusqm01t51bq9nmvs8ej3ikarg.apps.googleusercontent.com',
    iosBundleId: 'com.example.touchBarSoundpad',
  );
}
